### ISSUE TITLE
Stateful filter as annotation argument

### ISSUE THREAD

**Issue by sventschui** [PillowPillow/ng-annotations#3]
Wouldn't it be slightly more elegant to have a stateful attribute on the `@filter` attribute instead of defining a property?

e.g.

```
@filter(name='...', stateful=true)
```

I'd raise a PR if you'd appreciate this change

**Comment by PillowPillow** [comment]
I agree with you, it's more elegant but there is a problem with a second optional argument.
The name is already optional, so If we don't define it, we can't set the stateful attribute.

**Comment by PillowPillow** [comment]
I see only three solutions to add the stateful attribute.  
- declare a new property (implemented with the v0.1.11)

``` javascript
@filter()
class MyFilter {
    $stateful=true;
}
```
- add a new class decorator, working only with the filter decorator 

``` javascript
@filter()
@stateful
class MyFilter {}
```
- accept two differents argument type in the @filter decorator, a string for name or a literal object

``` javascript
@filter({name: 'MyFilter', stateful: true})
class MyFilter {}
```

I implemented the first solution to fix this issue because it was the simplest, but i like the third too.

**Comment by PillowPillow** [comment]
I updated the @filter decorator with v0.1.12.
Now the implemented solution is the third. The first could cause some naming conflicts. 
https://github.com/PillowPillow/ng-annotations#d_filter

**Comment by sventschui** [comment]
Great! Thanks
